<?xml version="1.0"?>
<robot name="salisbury_hand" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants -->
  <xacro:property name="PI" value="3.14159265359" />

  <!-- Kinematic parameters -->
  <xacro:property name="a1" value="0.1" />
  <xacro:property name="a2" value="0.1" />
  <xacro:property name="a3" value="0.05" />

  <!-- Finger base positions -->
  <xacro:property name="finger1_base" value="0.05 0 -0.05" />
  <xacro:property name="finger2_base" value="0.05 -0.05 0.05" />
  <xacro:property name="finger3_base" value="0.05 0.05 0.05" />

  <!-- Visual parameters -->
  <xacro:property name="joint_radius" value="0.02" />
  <xacro:property name="link_radius"  value="0.01" />

  <!-- Fingertip parameters -->
  <xacro:property name="h" value="0.02" />
  
  <!-- Global Materials -->
  <material name="sky_blue">
    <color rgba="0.53 0.81 0.92 1.0"/>
  </material>
  <material name="dark_blue">
    <color rgba="0 0 0.8 1.0"/>
  </material>
  <material name="purple">
    <color rgba="0.5 0 0.5 1.0"/>
  </material>

  <!-- The root link -->
  <link name="world"/>

  <!-- Macro to create a finger chain with custom parameters -->
  <xacro:macro name="finger" params="finger_id base_xyz invert theta_lower_joint0 theta_upper_joint0">
    
    <!-- Base Joint -->
    <link name="finger${finger_id}_base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${joint_radius}"/>
        </geometry>
        <material name="sky_blue"/>
      </visual>
    </link>
    <joint name="finger${finger_id}_base_fixed" type="fixed">
      <parent link="world"/>
      <child link="finger${finger_id}_base_link"/>
      <origin xyz="${base_xyz}" rpy="${(PI if invert else 0)} ${(-PI/4 if invert else PI/4)} 0"/>
    </joint>

    <!-- First Revolute Joint -->
    <link name="finger${finger_id}_joint0_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${joint_radius}"/>
        </geometry>
        <material name="sky_blue"/>
      </visual>
    </link>
    <joint name="finger${finger_id}_joint0" type="revolute">
      <parent link="finger${finger_id}_base_link"/>
      <child link="finger${finger_id}_joint0_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${theta_lower_joint0}" upper="${theta_upper_joint0}" effort="10" velocity="1"/>
    </joint>

    <!-- First Link -->
    <link name="finger${finger_id}_link0">
      <visual>
        <origin xyz="${-a1/2} 0 0" rpy="0 ${-(PI/2)} 0"/>
        <geometry>
          <cylinder radius="${link_radius}" length="${a1}"/>
        </geometry>
        <material name="dark_blue"/>
      </visual>
    </link>
    <joint name="finger${finger_id}_link0_fixed" type="fixed">
      <parent link="finger${finger_id}_joint0_link"/>
      <child link="finger${finger_id}_link0"/>
      <origin xyz="${a1} 0 0" rpy="${-(PI/2)} 0 0"/>
    </joint>

    <!-- Second Revolute Joint -->
    <link name="finger${finger_id}_joint1_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${joint_radius}"/>
        </geometry>
        <material name="sky_blue"/>
      </visual>
    </link>
    <joint name="finger${finger_id}_joint1" type="revolute">
      <parent link="finger${finger_id}_link0"/>
      <child link="finger${finger_id}_joint1_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-(PI/4)}" upper="${-(PI/2)}" effort="10" velocity="1"/>
    </joint>

    <!-- Second Link -->
    <link name="finger${finger_id}_link1">
      <visual>
        <origin xyz="${-(a2/2)} 0 0" rpy="0 ${-(PI/2)} 0"/>
        <geometry>
          <cylinder radius="${link_radius}" length="${a2}"/>
        </geometry>
        <material name="dark_blue"/>
      </visual>
    </link>
    <joint name="finger${finger_id}_link1_fixed" type="fixed">
      <parent link="finger${finger_id}_joint1_link"/>
      <child link="finger${finger_id}_link1"/>
      <origin xyz="${a2} 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Third Revolute Joint -->
    <link name="finger${finger_id}_joint2_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${joint_radius}"/>
        </geometry>
        <material name="sky_blue"/>
      </visual>
    </link>
    <joint name="finger${finger_id}_joint2" type="revolute">
      <parent link="finger${finger_id}_link1"/>
      <child link="finger${finger_id}_joint2_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-(PI/16)}" upper="${-(PI/4)}" effort="10" velocity="1"/>
    </joint>

    <!-- Third Link -->
    <link name="finger${finger_id}_link2">
      <visual>
        <origin xyz="${-(a3/2)+h} 0 0" rpy="0 ${-(PI/2)} 0"/>
        <geometry>
          <cylinder radius="${link_radius}" length="${a3 + h}"/>
        </geometry>
        <material name="dark_blue"/>
      </visual>
    </link>
    <joint name="finger${finger_id}_link2_fixed" type="fixed">
      <parent link="finger${finger_id}_joint2_link"/>
      <child link="finger${finger_id}_link2"/>
      <origin xyz="${a3} 0 0" rpy="0 0 0"/>
    </joint>

   <!-- Fingertip -->
    <link name="finger${finger_id}_tip">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${link_radius}"/>
        </geometry>
        <material name="purple"/>
      </visual>
    </link>
    <joint name="finger${finger_id}_tip_fixed" type="fixed">
      <parent link="finger${finger_id}_link2"/>
      <child link="finger${finger_id}_tip"/>
      <origin xyz="${h + link_radius} 0 0" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <!-- Instantiate fingers with custom parameters -->
  <xacro:finger finger_id="1" base_xyz="${finger1_base}" invert="false" theta_lower_joint0="${-(PI/8)}" theta_upper_joint0="${(PI/8)}"/>
  <xacro:finger finger_id="2" base_xyz="${finger2_base}" invert="true"  theta_lower_joint0="${-(PI/8)}"    theta_upper_joint0="${(PI/8)}"/>
  <xacro:finger finger_id="3" base_xyz="${finger3_base}" invert="true"  theta_lower_joint0="${-(PI/8)}"    theta_upper_joint0="${(PI/8)}"/>

</robot>