<?xml version="1.0"?>
<robot name="salisbury_hand" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants -->
  <xacro:property name="PI" value="3.14159265359" />

  <!-- Kinematic parameters -->
  <xacro:property name="a1" value="0.1" />
  <xacro:property name="a2" value="0.1" />
  <xacro:property name="a3" value="0.05" />

  <!-- Finger base positions -->
  <xacro:property name="base_distance" value="0.05" />
  <xacro:property name="finger1_base" value="${base_distance} 0 ${-base_distance}" />
  <xacro:property name="finger2_base" value="${base_distance} ${-base_distance} ${base_distance}" />
  <xacro:property name="finger3_base" value="${base_distance} ${base_distance} ${base_distance}" />

  <!-- Other parameters -->
  <xacro:property name="h" value="${a3/2}" />
  <xacro:property name="cylinder_radius" value="0.01" />
  <xacro:property name="r" value="${cylinder_radius}" />
  <xacro:property name="sphere_radius" value="${cylinder_radius*2}" />
  <xacro:property name="fingertip_x" value="0.267" />
  <xacro:property name="fingertip_y_range" value="0.10" />
  <xacro:property name="fingertip_z_range" value="0.034" /> 
  <xacro:property name="box_size_y_tolerance" value="0.05" />
  <xacro:property name="box_size_x" value="0.03" />
  <xacro:property name="box_size_y" value="${fingertip_y_range + box_size_y_tolerance}" />
  <xacro:property name="box_size_z" value="${fingertip_z_range - 2*r}" />

  <!-- Global Materials -->
  <material name="sky_blue">
    <color rgba="0.53 0.81 0.92 1.0"/>
  </material>
  <material name="dark_blue">
    <color rgba="0 0 0.8 1.0"/>
  </material>
  <material name="purple">
    <color rgba="0.5 0 0.5 1.0"/>
  </material>
  <material name="green">
    <color rgba="0 1.0 0 1.0"/>
  </material>

  <!-- The root link -->
  <link name="world"/>

  <!-- Helper macros for visuals -->
  <xacro:macro name="vis_sphere" params="radius material origin_xyz='0 0 0'">
    <visual>
      <origin xyz="${origin_xyz}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${radius}"/>
      </geometry>
      <material name="${material}"/>
    </visual>
  </xacro:macro>

  <xacro:macro name="vis_cylinder" params="length radius material origin_xyz rpy">
    <visual>
      <origin xyz="${origin_xyz}" rpy="${rpy}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
      <material name="${material}"/>
    </visual>
  </xacro:macro>

  <!-- Macro to create a finger chain -->
  <xacro:macro name="finger" params="finger_id base_xyz invert theta_lower_joint0 theta_upper_joint0">
    <link name="finger${finger_id}_base_joint">
      <xacro:vis_sphere radius="${sphere_radius}" material="sky_blue"/>
    </link>
    <joint name="finger${finger_id}_base_fixed" type="fixed">
      <parent link="world"/>
      <child link="finger${finger_id}_base_joint"/>
      <origin xyz="${base_xyz}" rpy="${(PI if invert else 0)} ${(-PI/4 if invert else PI/4)} 0"/>
    </joint>

    <link name="finger${finger_id}_joint0_visual">
      <xacro:vis_sphere radius="${sphere_radius}" material="sky_blue"/>
    </link>
    <joint name="finger${finger_id}_joint0" type="revolute">
      <parent link="finger${finger_id}_base_joint"/>
      <child link="finger${finger_id}_joint0_visual"/>
      <axis xyz="0 0 1"/>
      <limit lower="${theta_lower_joint0}" upper="${theta_upper_joint0}" effort="10" velocity="1"/>
    </joint>

    <link name="finger${finger_id}_link0_cylinder">
      <xacro:vis_cylinder length="${a1}" radius="${cylinder_radius}" material="dark_blue"
                          origin_xyz="${-a1/2} 0 0" rpy="0 ${-PI/2} 0"/>
    </link>
    <joint name="finger${finger_id}_link0_fixed" type="fixed">
      <parent link="finger${finger_id}_joint0_visual"/>
      <child link="finger${finger_id}_link0_cylinder"/>
      <origin xyz="${a1} 0 0" rpy="${-PI/2} 0 0"/>
    </joint>

    <link name="finger${finger_id}_joint1_visual">
      <xacro:vis_sphere radius="${sphere_radius}" material="sky_blue"/>
    </link>
    <joint name="finger${finger_id}_joint1" type="revolute">
      <parent link="finger${finger_id}_link0_cylinder"/>
      <child link="finger${finger_id}_joint1_visual"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-PI/4}" upper="${-PI/2}" effort="10" velocity="1"/>
    </joint>

    <link name="finger${finger_id}_link1_cylinder">
      <xacro:vis_cylinder length="${a2}" radius="${cylinder_radius}" material="dark_blue"
                          origin_xyz="${-a2/2} 0 0" rpy="0 ${-PI/2} 0"/>
    </link>
    <joint name="finger${finger_id}_link1_fixed" type="fixed">
      <parent link="finger${finger_id}_joint1_visual"/>
      <child link="finger${finger_id}_link1_cylinder"/>
      <origin xyz="${a2} 0 0"/>
    </joint>

    <link name="finger${finger_id}_joint2_visual">
      <xacro:vis_sphere radius="${sphere_radius}" material="sky_blue"/>
    </link>
    <joint name="finger${finger_id}_joint2" type="revolute">
      <parent link="finger${finger_id}_link1_cylinder"/>
      <child link="finger${finger_id}_joint2_visual"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-PI/16}" upper="${-PI/4}" effort="10" velocity="1"/>
    </joint>

    <link name="finger${finger_id}_link2_cylinder">
      <xacro:vis_cylinder length="${a3 + h}" radius="${cylinder_radius}" material="dark_blue"
                          origin_xyz="${-(a3/2)+h} 0 0" rpy="0 ${-PI/2} 0"/>
    </link>
    <joint name="finger${finger_id}_link2_fixed" type="fixed">
      <parent link="finger${finger_id}_joint2_visual"/>
      <child link="finger${finger_id}_link2_cylinder"/>
      <origin xyz="${a3} 0 0"/>
    </joint>

    <link name="finger${finger_id}_tip_visual">
      <xacro:vis_sphere radius="${r}" material="purple" origin_xyz="-${r} 0 0"/>
    </link>
    <joint name="finger${finger_id}_tip_fixed" type="fixed">
      <parent link="finger${finger_id}_link2_cylinder"/>
      <child link="finger${finger_id}_tip_visual"/>
      <origin xyz="${h + 2*r} 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Macro to create the box without a fixed joint (link only) -->
  <xacro:macro name="create_floating_box"
               params="box_name
                       box_size_x
                       box_size_y
                       box_size_z">
    <link name="${box_name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${box_size_x} ${box_size_y} ${box_size_z}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${box_size_x} ${box_size_y} ${box_size_z}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.2"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- Instantiate the 3 fingers -->
  <xacro:finger finger_id="1"
                base_xyz="${finger1_base}"
                invert="false"
                theta_lower_joint0="${-PI/8}"
                theta_upper_joint0="${PI/8}"/>
  <xacro:finger finger_id="2"
                base_xyz="${finger2_base}"
                invert="true"
                theta_lower_joint0="${-PI/8}"
                theta_upper_joint0="${PI/8}"/>
  <xacro:finger finger_id="3"
                base_xyz="${finger3_base}"
                invert="true"
                theta_lower_joint0="${-PI/8}"
                theta_upper_joint0="${PI/8}"/>

  <!-- Box that encloses the three fingertip coordinates when joints are centered -->
  <!-- <xacro:create_fixed_box
       box_name="grasp_box"
       box_size_x="${box_size_x}"
       box_size_y="${box_size_y}"
       box_size_z="${box_size_z}"
       xyz="${fingertip_x} 0 0"
       rpy="0 0 0"
       material_name="green"
  /> -->

  <!-- Definition of the box with 6 DOF using dummy joints -->
  <!-- 1) Fix the box base position with the desired offset -->
  <joint name="grasp_box_base_fixed" type="fixed">
    <parent link="world"/>
    <child link="grasp_box_base"/>
    <origin xyz="${fingertip_x} 0 0" rpy="0 0 0"/>
  </joint>
  <link name="grasp_box_base"/>

  <!-- 2) Create the box link (visual, collision, inertia) -->
  <xacro:create_floating_box box_name="grasp_box" box_size_x="${box_size_x}" box_size_y="${box_size_y}" box_size_z="${box_size_z}"/>

  <!-- 3) Dummy joint chain to provide 6 DOF from the base frame -->
  <!-- Translations -->
  <joint name="grasp_box_trans_x" type="prismatic">
    <parent link="grasp_box_base"/>
    <child link="grasp_box_trans_x_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1" upper="1" effort="10" velocity="1"/>
  </joint>
  <link name="grasp_box_trans_x_link"/>

  <joint name="grasp_box_trans_y" type="prismatic">
    <parent link="grasp_box_trans_x_link"/>
    <child link="grasp_box_trans_y_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1" upper="1" effort="10" velocity="1"/>
  </joint>
  <link name="grasp_box_trans_y_link"/>

  <joint name="grasp_box_trans_z" type="prismatic">
    <parent link="grasp_box_trans_y_link"/>
    <child link="grasp_box_trans_z_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1" upper="1" effort="10" velocity="1"/>
  </joint>
  <link name="grasp_box_trans_z_link"/>

  <!-- Rotations -->
  <joint name="grasp_box_rot_x" type="revolute">
    <parent link="grasp_box_trans_z_link"/>
    <child link="grasp_box_rot_x_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="1"/>
  </joint>
  <link name="grasp_box_rot_x_link"/>

  <joint name="grasp_box_rot_y" type="revolute">
    <parent link="grasp_box_rot_x_link"/>
    <child link="grasp_box_rot_y_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="1"/>
  </joint>
  <link name="grasp_box_rot_y_link"/>

  <joint name="grasp_box_rot_z" type="revolute">
    <parent link="grasp_box_rot_y_link"/>
    <child link="grasp_box"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="1"/>
  </joint>

  <!-- Finger 1 contact reference frame on the box -->
  <link name="finger1_box_contact_frame"/>
  <joint name="finger1_box_contact_frame_joint" type="fixed">
    <parent link="grasp_box"/>
    <child link="finger1_box_contact_frame"/>
    <origin xyz="0.006 0.000 -0.009" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- Finger 2 contact reference frame on the box -->
  <link name="finger2_box_contact_frame"/>
  <joint name="finger2_box_contact_frame_joint" type="fixed">
    <parent link="grasp_box"/>
    <child link="finger2_box_contact_frame"/>
    <origin xyz="0.007 -0.050 0.009" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- Finger 3 contact reference frame on the box -->
  <link name="finger3_box_contact_frame"/>
  <joint name="finger3_box_contact_frame_joint" type="fixed">
    <parent link="grasp_box"/>
    <child link="finger3_box_contact_frame"/>
    <origin xyz="0.006 0.050 0.009" rpy="0.0 0.0 0.0"/>
  </joint>

</robot>